// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: subscription.proto

package subscription

import fmt "fmt"
import github_com_mwitkow_go_proto_validators "github.com/mwitkow/go-proto-validators"
import proto "github.com/gogo/protobuf/proto"
import math "math"
import _ "github.com/gogo/protobuf/gogoproto"
import _ "github.com/mwitkow/go-proto-validators"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

func (this *SubscriptionRequest) Validate() error {
	if this.SubscriptionId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("SubscriptionId", fmt.Errorf(`value '%v' must not be an empty string`, this.SubscriptionId))
	}
	return nil
}
func (this *SubscriptionResponse) Validate() error {
	return nil
}
func (this *GroupRequest) Validate() error {
	if this.UserId == "" {
		return github_com_mwitkow_go_proto_validators.FieldError("UserId", fmt.Errorf(`value '%v' must not be an empty string`, this.UserId))
	}
	return nil
}
func (this *GroupResponse) Validate() error {
	return nil
}
